using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace r6_marketplace.Utils
{
    internal class RequestBodies
    {
        internal const string GetItemData =
            "[{\"operationName\":\"GetItemDetails\",\"variables\":{\"spaceId\":\"0d2ae42d-4c27-4cb7-af6c-2099062302bb\",\"itemId\":\"{ITEMID}\",\"tradeId\":\"\",\"fetchTrade\":false},\"query\":\"query GetItemDetails($spaceId: String!, $itemId: String!, $tradeId: String!, $fetchTrade: Boolean!) {  game(spaceId: $spaceId) {    id    marketableItem(itemId: $itemId) { id item {   ...SecondaryStoreItemFragment   ...SecondaryStoreItemOwnershipFragment   __typename } marketData {   ...MarketDataFragment   __typename } paymentLimitations {   id   paymentItemId   minPrice   maxPrice   __typename } __typename    }    viewer { meta {   id   trades(filterBy: {states: [Created], itemIds: [$itemId]}) {     nodes {  ...TradeFragment  __typename     }     __typename   }   trade(tradeId: $tradeId) @include(if: $fetchTrade) {     ...TradeFragment     __typename   }   __typename } __typename    }    __typename  }}fragment SecondaryStoreItemFragment on SecondaryStoreItem {  id  assetUrl  itemId  name  tags  type  __typename}fragment SecondaryStoreItemOwnershipFragment on SecondaryStoreItem {  id  viewer {    meta { id isOwned quantity __typename    }    __typename  }  __typename}fragment MarketDataFragment on MarketableItemMarketData {  id  sellStats {    id    paymentItemId    lowestPrice    highestPrice    activeCount    __typename  }  buyStats {    id    paymentItemId    lowestPrice    highestPrice    activeCount    __typename  }  lastSoldAt {    id    paymentItemId    price    performedAt    __typename  }  __typename}fragment TradeFragment on Trade {  id  tradeId  state  category  createdAt  expiresAt  lastModifiedAt  failures  tradeItems {    id    item { ...SecondaryStoreItemFragment ...SecondaryStoreItemOwnershipFragment __typename    }    __typename  }  payment {    id    item { ...SecondaryStoreItemQuantityFragment __typename    }    price    transactionFee    __typename  }  paymentOptions {    id    item { ...SecondaryStoreItemQuantityFragment __typename    }    price    transactionFee    __typename  }  paymentProposal {    id    item { ...SecondaryStoreItemQuantityFragment __typename    }    price    __typename  }  viewer {    meta { id tradesLimitations {   ...TradesLimitationsFragment   __typename } __typename    }    __typename  }  __typename}fragment SecondaryStoreItemQuantityFragment on SecondaryStoreItem {  id  viewer {    meta { id quantity __typename    }    __typename  }  __typename}fragment TradesLimitationsFragment on UserGameTradesLimitations {  id  buy {    id    resolvedTransactionCount    resolvedTransactionPeriodInMinutes    activeTransactionCount    __typename  }  sell {    id    resolvedTransactionCount    resolvedTransactionPeriodInMinutes    activeTransactionCount    resaleLocks { id itemId expiresAt __typename    }    __typename  }  __typename}\"}]";
        internal const string GetItemPriceHistoryData =
            "[{\"operationName\":\"GetItemPriceHistory\",\"variables\":{\"spaceId\":\"0d2ae42d-4c27-4cb7-af6c-2099062302bb\",\"itemId\":\"{ITEMID}\",\"paymentItemId\":\"9ef71262-515b-46e8-b9a8-b6b6ad456c67\"},\"query\":\"query GetItemPriceHistory($spaceId: String!, $itemId: String!, $paymentItemId: String!) {\\n  game(spaceId: $spaceId) {\\n    id\\n    marketableItem(itemId: $itemId) {\\n      id\\n      priceHistory(paymentItemId: $paymentItemId) {\\n        id\\n        date\\n        lowestPrice\\n        averagePrice\\n        highestPrice\\n        itemsCount\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\"}]";
        internal const string GetSearchTagsData =
            "[\r\n    {\r\n        \"operationName\": \"GetMarketplaceGameConfig\",\r\n        \"variables\": {\r\n            \"spaceId\": \"0d2ae42d-4c27-4cb7-af6c-2099062302bb\"\r\n        },\r\n        \"query\": \"query GetMarketplaceGameConfig($spaceId: String!) {\\n  game(spaceId: $spaceId) {\\n    id\\n    marketplace {\\n      assets {\\n        backgroundImage\\n        homeAssets {\\n          buyTab\\n          sellTab\\n          transactionsTab\\n          __typename\\n        }\\n        __typename\\n      }\\n      privilege {\\n        tradePrivilegeId\\n        __typename\\n      }\\n      currency {\\n        currencyId\\n        currencyUrl\\n        __typename\\n      }\\n      contact {\\n        bugUrl\\n        bugLabel\\n        __typename\\n      }\\n      tags {\\n        color\\n        value\\n        iconUrl\\n        displayName\\n        __typename\\n      }\\n      tagGroups {\\n        type\\n        values\\n        displayName\\n        __typename\\n      }\\n      types {\\n        value\\n        iconUrl\\n        displayName\\n        __typename\\n      }\\n      homeTypes {\\n        value\\n        displayName\\n        iconUrl\\n        __typename\\n      }\\n      filters {\\n        categoryId\\n        type\\n        displayName\\n        sortType\\n        sortDirection\\n        values {\\n          value\\n          displayName\\n          __typename\\n        }\\n        __typename\\n      }\\n      recommendations {\\n        userItemRecommendations {\\n          projectId\\n          categoryId\\n          __typename\\n        }\\n        __typename\\n      }\\n      tabConfig {\\n        buy {\\n          filterSelection {\\n            categoryId\\n            values\\n            __typename\\n          }\\n          sortSelection {\\n            field\\n            direction\\n            orderType\\n            __typename\\n          }\\n          __typename\\n        }\\n        sell {\\n          filterSelection {\\n            categoryId\\n            values\\n            __typename\\n          }\\n          sortSelection {\\n            field\\n            direction\\n            orderType\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      userResearch {\\n        link\\n        linkId\\n        homeBanner {\\n          iconUrl\\n          title\\n          description\\n          buttonLabel\\n          __typename\\n        }\\n        footerLink {\\n          iconUrl\\n          buttonLabel\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\"\r\n    }\r\n]";
    }
}
